name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    name: Lint + TypeCheck + Build + Smoke + E2E
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install deps
        run: npm ci
        working-directory: digital-pin-llc

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: digital-pin-llc/services/frontend-next

      - name: Lint
        run: npm run lint --workdir services/frontend-next || npm run lint
        working-directory: digital-pin-llc

      - name: Type Check
        run: (cd services/frontend-next && npx tsc --noEmit)
        working-directory: digital-pin-llc

      - name: Build
        run: (cd services/frontend-next && npm run build)
        working-directory: digital-pin-llc

      - name: Smoke
        run: (cd services/frontend-next && npm run smoke)
        working-directory: digital-pin-llc

      - name: E2E Tests
        run: (cd services/frontend-next && npm run test:e2e:ci)
        working-directory: digital-pin-llc

      - name: Upload Playwright Report (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.node }}
          path: digital-pin-llc/services/frontend-next/playwright-report
          if-no-files-found: ignore

      - name: Artifact (Build output)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.node }}
          path: digital-pin-llc/services/frontend-next/.next
          if-no-files-found: ignore
